USE [master]
GO

CREATE DATABASE [exam_DBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'exam_DBD', FILENAME = N'.\exam_DBD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'exam_DBD_log', FILENAME = N'.\exam_DBD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [exam_DBD] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [exam_DBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [exam_DBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [exam_DBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [exam_DBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [exam_DBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [exam_DBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [exam_DBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [exam_DBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [exam_DBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [exam_DBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [exam_DBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [exam_DBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [exam_DBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [exam_DBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [exam_DBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [exam_DBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [exam_DBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [exam_DBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [exam_DBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [exam_DBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [exam_DBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [exam_DBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [exam_DBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [exam_DBD] SET RECOVERY FULL 
GO

ALTER DATABASE [exam_DBD] SET  MULTI_USER 
GO

ALTER DATABASE [exam_DBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [exam_DBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [exam_DBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [exam_DBD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [exam_DBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [exam_DBD] SET  READ_WRITE 
GO